API_KEY_AVI = '1f67d5c737a3b09f7850f67574c3112c'
API_KEY_TRN = 'b553ddc4-f6db-4d6e-bc3a-cde7801110c2'
city_to_iata = {
    'Москва': 'mow',
    'Санкт-Петербург': 'led',
    'Казань': 'kzn',
    'Екатеринбург': 'svx',
    'Москва (Внуково)': 'vko',
    'Анапа': 'aae',
    'Абакан': 'aba',
    'Ачинск': 'acs',
    'Алдан': 'adh',
    'Сочи': 'aer',
    'Амдерма': 'amv',
    'Архангельск': 'arh',
    'Астрахань': 'asf',
    'Барнаул': 'bax',
    'Белурек': 'bcx',
    'Белая Гора': 'bgn',
    'Богучаны': 'bgs',
    'Баджкит': 'bka',
    'Богородское': 'bqg',
    'Батагай': 'bqj',
    'Благовещенск': 'bqs',
    'Братск': 'btk',
    'Бованенково': 'bvj',
    'Буревестник': 'bvv',
    'Балаково': 'bwo',
    'Брянск': 'bzk',
    'Череповец': 'cee',
    'Челябинск': 'cek',
    'Чокурдах': 'ckh',
    'Чкаловский': 'ckl',
    'Соловки': 'csh',
    'Чебоксары': 'csy',
    'Черский': 'cyx',
    'Чара': 'czr',
    'Менделеево': 'dee',
    'Дальнегорск': 'dhg',
    'Диксон': 'dks',
    'Дальнереченск': 'dlr',
    'Депутатский': 'dpt',
    'Анадырь': 'dyr',
    'Белгород': 'ego',
    'Енисейск': 'eie',
    'Ейск': 'eik',
    'Шахтёрск': 'eks',
    'Ербогачён': 'erg',
    'Элиста': 'esl',
    'Светлая': 'etl',
    'Белоярский': 'eyk',
    'Берёзово': 'ezv',
    'Магдагачи': 'gdg',
    'Магадан': 'gdx',
    'Геленджик': 'gdz',
    'Нижний Новгород': 'goj',
    'Туру': 'goy',
    'Грозный': 'grv',
    'Май-Гатка': 'gvn',
    'Маган': 'gyg',
    'Ханты-Мансийск': 'hma',
    'Чита': 'hta',
    'Хатанга': 'htg',
    'Игарка': 'iaa',
    'Ярославль': 'iar',
    'Магас': 'igt',
    'Ижевск': 'ijk',
    'Тикси': 'iks',
    'Иркутск': 'ikt',
    'Инта': 'ina',
    'Игра': 'irm',
    'Итуруп': 'itu',
    'Иваново': 'iwa',
    'Йошкар-Ола': 'jok',
    'Киренск': 'kck',
    'Кемерово': 'kej',
    'Калининград': 'kgd',
    'Когалым': 'kgp',
    'Хабаровск': 'khv',
    'Красноярск': 'kja',
    'Красноселькуп': 'kkq',
    'Тверь': 'kld',
    'Калуга': 'klf',
    'Кодинск': 'kny',
    'Кепервеем': 'kpw',
    'Курган': 'kro',
    'Краснодар': 'krr',
    'Котлас': 'ksz',
    'Самара': 'kuf',
    'Кировск': 'kvk',
    'Марково': 'kvm',
    'Кавалерово': 'kvr',
    'Киров': 'kvx',
    'Комсомольск-на-Амуре': 'kxk',
    'Кызыл': 'kyz',
    'Лешуконское': 'ldg',
    'Смоленск': 'lnx',
    'Липецк': 'lpk',
    'Махачкала': 'mcx',
    'Мотыгино': 'mjy',
    'Мирный': 'mjz',
    'Мурманск': 'mmk',
    'Магнитогорск': 'mqf',
    'Мама': 'mqj',
    'Минеральные Воды': 'mrv',
    'Нальчик': 'nal',
    'Бегишево': 'nbc',
    'Нефтекамск': 'nef',
    'Терней': 'nei',
    'Нерюнгри': 'ner',
    'Ноглики': 'ngk',
    'Нижневартовск': 'njc',
    'Николаевск-на-Амуре': 'nli',
    'Нарьян-Мар': 'nnm',
    'Новороссийск': 'noi',
    'Ноябрьск': 'noj',
    'Новокузнецк': 'noz',
    'Норильск': 'nsk',
    'Новый Уренгой': 'nux',
    'Новгород': 'nvr',
    'Нягань': 'nya',
    'Надым': 'nym',
    'Нюрба': 'nyr',
    'Нижнеангарск': 'nzg',
    'Бодайбо': 'odo',
    'Орёл': 'oel',
    'Владикавказ': 'ogz',
    'Новостройка': 'ohh',
    'Охотск': 'oho',
    'Октябрьский': 'okt',
    'Олёкминск': 'olz',
    'Омск': 'oms',
    'Оленёк': 'onk',
    'Орск': 'osw',
    'Новосибирск': 'ovb',
    'Советский': 'ovs',
    'Пермь': 'pee',
    'Петрозаводск': 'pes',
    'Печора': 'pex',
    'Пенза': 'pez',
    'Петропавловск-Камчатский': 'pkc',
    'Псков': 'pkv',
    'Провидения': 'pvs',
    'Певек': 'pwe',
    'Полярный': 'pyj',
    'Радужный': 'rat',
    'Оренбург': 'ren',
    'Горно-Алтайск': 'rgk',
    'Тобольск': 'rmz',
    'Ростов-на-Дону': 'rov',
    'Саратов': 'rtw',
    'Рыбинск': 'ryb',
    'Преображение': 'rzh',
    'Рязань': 'rzn',
    'Сабетта': 'sbt',
    'Сыктывкар': 'scw',
    'Среднеколымск': 'sek',
    'Светлогорск': 'ses',
    'Сургут': 'sgc',
    'Саранск': 'skx',
    'Ставрополь': 'stw',
    'Сахалин': 'suk',
    'Сангар': 'suy',
    'Стрежевой': 'swt',
    'Северо-Эвенск': 'swv',
    'Саскылах': 'sys',
    'Тамбов': 'tbw',
    'Таганрог': 'tgk',
    'Подкаменная Тунгуска': 'tgp',
    'Туруханск': 'thx',
    'Тюмень': 'tjm',
    'Тиксимо': 'tkm',
    'Талакан': 'tlk',
    'Пластун': 'tly',
    'Томск': 'tof',
    'Тарко-Сале': 'tql',
    'Тула': 'tya',
    'Тында': 'tyd',
    'Ухта': 'uct',
    'Уренгой': 'uen',
    'Уфа': 'ufa',
    'Усть-Илимск': 'uik',
    'Усть-Куйга': 'ukg',
    'Усть-Кут': 'ukx',
    'Ленск': 'ulk',
    'Ульяновск': 'uly',
    'Усть-Мая': 'ums',
    'Урай': 'urj',
    'Курск': 'urs',
    'Усинск': 'usk',
    'Усть-Рена': 'usr',
    'Усть-Цильма': 'uts',
    'Бугульма': 'uua',
    'Улан-Удэ': 'uud',
    'Южно-Сахалинск': 'uus',
    'Ванавара': 'vaq',
    'Северо-Энисейск': 'veo',
    'Вологда': 'vgd',
    'Верхневилюйск': 'vhv',
    'Воркута': 'vkt',
    'Волгодонск': 'vlk',
    'Великие Луки': 'vlu',
    'Волгоград': 'vog',
    'Воронеж': 'voz',
    'Варандей': 'vri',
    'Великий Устюг': 'vus',
    'Владивосток': 'vvo',
    'Вилюйск': 'vyi',
    'Ярцево': 'yae',
    'Якутск': 'yks',
    'Мыс Каменный': 'ymk',
    'Чиганка': 'zix',
    'Зырянка': 'zkp',
    'Зональное': 'zzo',
    'Адамовка': 'adm',
    'Агзу': 'azu',
    'Амгу': 'amu',
    'Апука': 'apu',
    'Архыз': 'ahz',
    'Ахайваям': 'ach',
    'Аянка': 'ayk',
    'Аян': 'ayn',
    'Главный': 'bgg',
    'Белокуриха': 'bih',
    'Беринговский': 'bng',
    'Большой Ларджак': 'bok',
    'Бурный': 'buy',
    'Байлино': 'byl',
    'Спайск': 'vag',
    'Вершинский': 'ves',
    'Владимир': 'vlm',
    'Вампугольск': 'vmp',
    'Вуктыл': 'vtl',
    'Домбай': 'dmy',
    'Эдинка': 'edi',
    'Эссей': 'esi',
    'Ессентуки': 'esn',
    'Железногорск': 'zhez',
    'Зея': 'zeya',
    'Лаврентия': 'zla',
    'Крабозаводское': 'kbz',
    'Кускургун': 'kgy',
    'Кедровый': 'kdd',
    'Каменское': 'kdu',
    'Кузьмовка': 'kzv',
    'Казачинское': 'kzch',
    'Корлики': 'kiu',
    'Колекеган': 'klk',
    'Краснокаменск': 'knk',
    'Кослан': 'kos',
    'Красный Чикой': 'ksch',
    'Красный Кут': 'ksy',
    'Кислоканы': 'ksyu',
    'Куджумба': 'kyum',
    'Лайтамак': 'lay',
    'Ларджак': 'lry',
    'Мама': 'mam',
    'Мириуга': 'mga',
    'Мезень': 'mzn',
    'Манилы': 'mil',
    'Максимовка': 'mki',
    'Никольское': 'nik',
    'Нелькан': 'nln',
    'Новокуровка': 'nuv',
    'Озерная': 'ozr',
    'Омолон': 'ool',
    'Оссора': 'oso',
    'Омсукчан': 'osu',
    'Ошарово': 'osha',
    'Поронайск': 'pay',
    'Палана': 'pan',
    'Пахачи': 'pach',
    'Победа': 'pbe',
    'Полигус': 'pgu',
    'Подволочное': 'pdv',
    'Полынья Осипенко': 'pos',
    'Мопный Курт': 'pug',
    'Покур': 'pur',
    'Сангар': 'sag',
    'Суломай': 'sai',
    'Соболево': 'sbo',
    'Сосновый Бор': 'sbr',
    'Суринда': 'sdr',
    'Северо-Курильск': 'skr',
    'Светлый': 'sly',
    'Слаутное': 'slu',
    'Самарга': 'smg',
    'Смирных': 'smh',
    'Сеймчан': 'smch',
    'Синегорье': 'sng',
    'Старый Оскол': 'sol',
    'Средние Пахачи': 'sph',
    'Сусуман': 'ssm',
    'Срелка-Чуня': 'schu',
    'Тигиль': 'tig',
    'Тиличики': 'til',
    'Таловка': 'tlo',
    'Тутончаны': 'tnch',
    'Тугур': 'tuu',
    'Троицко-Печорск': 'tcp',
    'Толка': 'tyk',
    'Удское': 'uds',
    'Усть-Кокса': 'uko',
    'Усть-Камчатск': 'ukch',
    'Учами': 'umi',
    'Усть-Омчуг': 'uom',
    'Усть-Коликиджиган': 'ute',
    'Усть-Хайрюзово': 'uhy',
    'Хайлино': 'hai',
    'Харута': 'hau',
    'Хужир': 'hzhr',
    'Керпучи': 'hrp',
    'Чегдомын': 'chd',
    'Химдалск': 'chem',
    'Чехломей': 'chekh',
    'Чиринда': 'chir',
    'Чумикан': 'chmi',
    'Шерегеш': 'shgsh',
    'Шушенское': 'shush',
    'Залив Креста': 'egt',
    'Эконда': 'eko',
    'Джукта': 'ykt',
    'Ягодное': 'yago',
    'Ямбург': 'yamb',
'Нью-Йорк': 'nyc',  # John F. Kennedy International Airport (JFK), Newark Liberty International Airport (EWR), LaGuardia Airport (LGA)
    'Лос-Анджелес': 'lax',  # Los Angeles International Airport
    'Чикаго': 'ord',  # O'Hare International Airport
    'Торонто': 'yyz',  # Toronto Pearson International Airport
    'Мехико': 'mex',  # Mexico City International Airport
    'Лондон': 'lon',  # Heathrow Airport (LHR), Gatwick Airport (LGW), Stansted Airport (STN)
    'Париж': 'par',  # Charles de Gaulle Airport (CDG), Orly Airport (ORY)
    'Берлин': 'ber',  # Berlin Brandenburg Airport
    'Рим': 'rom',  # Leonardo da Vinci–Fiumicino Airport (FCO), Ciampino Airport (CIA)
    'Мадрид': 'mad',  # Adolfo Suárez Madrid–Barajas Airport
    'Амстердам': 'ams',  # Amsterdam Schiphol Airport
    'Стамбул': 'ist',  # Istanbul Airport
    'Пекин': 'bjs',  # Beijing Capital International Airport (PEK), Beijing Daxing International Airport (PKX)
    'Шанхай': 'sha',  # Shanghai Pudong International Airport (PVG), Shanghai Hongqiao International Airport (SHA)
    'Токио': 'tyo',  # Narita International Airport (NRT), Haneda Airport (HND)
    'Сеул': 'sel',  # Incheon International Airport (ICN), Gimpo International Airport (GMP)
    'Сингапур': 'sin',  # Singapore Changi Airport
    'Бангкок': 'bkk',  # Suvarnabhumi Airport
    'Дубай': 'dxb',  # Dubai International Airport
    'Нью-Дели': 'del',  # Indira Gandhi International Airport
    'Мумбаи': 'bom',  # Chhatrapati Shivaji Maharaj International Airport
    'Кейптаун': 'cpt',  # Cape Town International Airport
    'Сидней': 'syd',  # Sydney Kingsford Smith Airport
    'Мельбурн': 'mel',  # Melbourne Airport (MEL), Avalon Airport (AVV)
    'Буэнос-Айрес': 'bue',  # Ministro Pistarini International Airport (EZE), Aeroparque Jorge Newbery (AEP)
    'Сан-Паулу': 'sao'  # São Paulo-Guarulhos International Airport (GRU), Congonhas Airport (CGH)
}
